import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "@/app/assets/logo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">
     
        <div className="h-[100px] bg-white flex items-center px-12">
          <Image src={logo} alt="logo" />
        </div>
        <body className={inter.className}>{children}</body>
     
    </div>
  );
}
