import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import SideBar from "./ui/dashboard/sidebar";
import { useSession } from "next-auth/react";
import { AppContextProvider } from "./store/context";

const nunito = Nunito({
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <AppContextProvider>
          <div className="flex flex-col w-screen">
            <Navbar />
            <div className="">{children}</div>
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
